name: Build and Push

on:
  pull_request:
    types:
      - closed
    branches:
      - main


env:
  AWS_ECR_NAME : "ait_onboarding_app"
  AWS_ROLE_TO_ASSUME_ARN: "arn:aws:iam::058264257313:role/ait-onboarding-app-github-ecr-access"
  AWS_REGION: "eu-west-1"
  AWS_ACCOUNT: "058264257313"


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Some tests
      run: echo "Add some tests here eventually ..."
  build-push-docker-image:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3
    - name: Install buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
    - name: Configure AWS creds to access ECR
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME_ARN }}
        role-session-name: github-ecr-session
        aws-region: ${{ env.AWS_REGION }}
    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registries: ${{ env.AWS_ACCOUNT }}
        mask-password: "true" # see: https://github.com/aws-actions/amazon-ecr-login#docker-credentials          
    - name: Build, tag, and push docker image to Amazon ECR
      run: |
        IMG_TAG=`cat VERSION`
        IMG_FULL_NAME="${{ env.AWS_ACCOUNT }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.AWS_ECR_NAME }}:${IMG_TAG}"
        docker buildx build --push \
        -t ${IMG_FULL_NAME} \
        --platform linux/amd64,linux/arm64 .
        # Configure the env var, so it can be used on the next GA steps
        echo "IMG_TAG=${IMG_TAG}" >> "$GITHUB_ENV"
    - name: Update the CD repo to trigger deployment
      env:
        DEPLOY_KEY: ${{ secrets.PRIV_SSH_KEY_BITBUCKET }}
        CD_REPO_URL: "git@bitbucket.org:automatitdevops/sergiib-skel.git"
        CD_REPO_NAME: "sergiib-skel"
        HELM_VALUES_F: "argocd/ait-onboarding-app/app-env/dev-values.yaml" # Relative to the CD_REPO_NAME repo
      run: |
        # Setup SSH for Bitbucket
        mkdir -p ~/.ssh
        echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan bitbucket.org >> ~/.ssh/known_hosts
        
        # Clone CD repo
        git clone ${CD_REPO_URL}
        cd ${CD_REPO_NAME}
        
        # Update Helm chart with new image tag
        sed -i -e "s/tag: \".*\"/tag: \"${IMG_TAG}\"/" ${HELM_VALUES_F}
        
        # Commit and push changes
        git config user.name 'GitHub Actions'
        git config user.email 'actions@github.com'
        git add ${HELM_VALUES_F}
        git commit -m "Update image tag to ${IMG_TAG}"
        git push origin main
