name: Build and Push

on:
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - main

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Some tests
      run: echo "Add some tests here eventually ..."

